services:
  # Backend Web Service
  - type: web
    name: calcom-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb://Rudra:12345gthy%25%26%29%26%5E%23%24GYgghhhh@ac-cjnni4s-shard-00-00.vcqm82y.mongodb.net:27017,ac-cjnni4s-shard-00-01.vcqm82y.mongodb.net:27017,ac-cjnni4s-shard-00-02.vcqm82y.mongodb.net:27017/calcom_clone?ssl=true&replicaSet=atlas-tuueog-shard-0&authSource=admin&appName=CalCluster
      - key: JWT_SECRET
        value: supersecretjwtkey_for_calcom_clone

  # Frontend Static Site
  - type: web
    name: calcom-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
